### ISSUE TITLE
There is no binary

### ISSUE THREAD

**Issue by ciaranmcnulty** [MarcelloDuarte/eris-runner#1]
Did you exclude `/bin`?

**Comment by MarcelloDuarte** [comment]
fixed in 7426e4885c128acc2c834d438bb22645022cdcc2

**Comment by MarcelloDuarte** [comment]
Forgot to commit the bin folder itself... 2 minutes!

**Comment by MarcelloDuarte** [comment]
And here it is 58556265aee94a98d995459c2c3db32391a25fbb
